# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-05 08:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[(b'HD', b'HONDA'), (b'HY', b'HYUNDAI'), (b'MS', b'MARUTI SUZUKI'), (b'TT', b'TATA'), (b'MH', b'MAHINDRA'), (b'TY', b'TOYOTA')], default='MH', max_length=2)),
                ('model_name', models.CharField(max_length=256)),
                ('model_no', models.CharField(max_length=256)),
                ('max_pass', models.IntegerField(default=0)),
                ('vehicle_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.TextField(max_length=256)),
                ('district', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taptez.VendorProfile'),
        ),
    ]
